# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-07 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endagaweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='sub_vacuum_grace_days',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='valid_through',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='sub_vacuum_inactive_days',
            field=models.IntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
