# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-04 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endagaweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bts',
            options={'default_permissions': (), 'permissions': (('view_bts', 'View BTS(Tower)'), ('add_bts', 'Add BTS(Tower)'), ('change_bts', 'Change BTS(Tower)'), ('deregister_bts', 'Deregister BTS(Tower)'), ('download_bts', 'Download BTS(Tower)'))},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'default_permissions': (), 'permissions': (('view_network', 'View network'), ('change_network', 'Change network'))},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'default_permissions': (), 'permissions': (('view_subscriber', 'View subscriber list'), ('change_subscriber', 'Edit subscriber'), ('deactive_subscriber', 'Deactive subscriber'))},
        ),
        migrations.AlterModelOptions(
            name='usageevent',
            options={'default_permissions': (), 'permissions': (('view_usage', 'View usage activities'), ('download_usage', 'Download usage activities'))},
        ),
    ]
