# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-03 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endagaweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'managed': False, 'permissions': (('view_credit', 'View credit adjustment'),)},
        ),
        migrations.AlterModelOptions(
            name='graph',
            options={'managed': False, 'permissions': (('view_graph', 'View graph'), ('download_graph', 'Download graph'))},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': False, 'permissions': (('view_report', 'View reports'), ('download_report', 'Download reports'))},
        ),
        migrations.AlterModelOptions(
            name='smsbroadcast',
            options={'managed': False, 'permissions': (('view_sms', 'View SMS broadcast'),)},
        ),
        migrations.AlterModelOptions(
            name='tower',
            options={'managed': False, 'permissions': (('view_tower', 'View tower'), ('download_tower', 'Download tower'))},
        ),
    ]
