# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endagaweb', '0002_auto_20170503_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('view_notification', 'View Notification'),),
            },
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'permissions': (('view_subscriber', 'View subscriber list'),)},
        ),
    ]
