# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-03 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endagaweb', '0003_auto_20170503_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bts',
            options={'managed': False, 'permissions': (('view_bts', 'View BTS'), ('download_bts', 'Download BTS'))},
        ),
    ]
